ERROR_CATALOG = [
    {
        "code": "invalid_request",
        "http_status": 400,
        "category": "request",
        "retryable": False,
        "message": "La requete est mal formee ou le JSON est invalide.",
        "frontend_action": "Corriger le format de la requete avant de reessayer.",
    },
    {
        "code": "validation_error",
        "http_status": 422,
        "category": "request",
        "retryable": False,
        "message": "Un ou plusieurs champs sont invalides.",
        "frontend_action": "Afficher les champs invalides et corriger les valeurs.",
    },
    {
        "code": "authentication_required",
        "http_status": 401,
        "category": "auth",
        "retryable": False,
        "message": "Un token utilisateur ou service est requis.",
        "frontend_action": "Reconnecter l'utilisateur ou verifier le token service.",
    },
    {
        "code": "forbidden",
        "http_status": 403,
        "category": "auth",
        "retryable": False,
        "message": "Le role courant ne permet pas cette action.",
        "frontend_action": "Masquer l'action ou demander un compte autorise.",
    },
    {
        "code": "service_token_invalid",
        "http_status": 401,
        "category": "auth",
        "retryable": False,
        "message": "Le token service S2S est invalide ou signe par une cle inconnue.",
        "frontend_action": "Verifier le token service emis par DiddiFreeID.",
    },
    {
        "code": "service_client_id_invalid",
        "http_status": 401,
        "category": "auth",
        "retryable": False,
        "message": "Le header X-Client-ID ne correspond pas au token service.",
        "frontend_action": "Verifier la configuration du client service appelant.",
    },
    {
        "code": "service_token_inactive",
        "http_status": 403,
        "category": "auth",
        "retryable": False,
        "message": "Le client service S2S n'est pas actif.",
        "frontend_action": "Verifier le statut du client dans DiddiFreeID.",
    },
    {
        "code": "service_not_allowed",
        "http_status": 403,
        "category": "auth",
        "retryable": False,
        "message": "Le service appelant n'est pas autorise sur cette integration.",
        "frontend_action": "Verifier le sujet du token service et l'integration appelee.",
    },
    {
        "code": "service_scope_invalid",
        "http_status": 403,
        "category": "auth",
        "retryable": False,
        "message": "Le token service ne contient pas le scope requis.",
        "frontend_action": "Demander un token service avec le scope attendu.",
    },
    {
        "code": "trace_not_found",
        "http_status": 404,
        "category": "map_trace",
        "retryable": False,
        "message": "La trace GPS demandee est introuvable.",
        "frontend_action": "Verifier l'identifiant de trace ou recreer une trace.",
    },
    {
        "code": "trace_already_finished",
        "http_status": 409,
        "category": "map_trace",
        "retryable": False,
        "message": "La trace GPS est deja terminee.",
        "frontend_action": "Ne plus envoyer de positions; utiliser l'etat existant.",
    },
    {
        "code": "trace_not_accepting_positions",
        "http_status": 409,
        "category": "map_trace",
        "retryable": False,
        "message": "La trace GPS n'accepte plus de positions.",
        "frontend_action": "Arreter l'envoi de positions pour cette trace.",
    },
    {
        "code": "trace_not_started",
        "http_status": 409,
        "category": "map_trace",
        "retryable": False,
        "message": "La trace GPS ne peut pas etre terminee car elle n'est pas demarree.",
        "frontend_action": "Recreer une trace ou ignorer la trace pour le scoring.",
    },
    {
        "code": "trace_not_finished",
        "http_status": 409,
        "category": "map_trace",
        "retryable": False,
        "message": "La trace GPS doit etre terminee avant analyse.",
        "frontend_action": "Appeler finish avant analyze, ou ignorer si deja abandonnee.",
    },
    {
        "code": "out_of_coverage",
        "http_status": 409,
        "category": "routing",
        "retryable": False,
        "message": "Le point demande est hors zone couverte.",
        "frontend_action": "Demander un autre point de depart ou d'arrivee.",
    },
    {
        "code": "no_route_found",
        "http_status": 404,
        "category": "routing",
        "retryable": False,
        "message": "Aucun itineraire n'a ete trouve.",
        "frontend_action": "Proposer un autre depart ou une autre destination.",
    },
    {
        "code": "routing_engine_unavailable",
        "http_status": 503,
        "category": "routing",
        "retryable": True,
        "message": "Le moteur OSRM est indisponible.",
        "frontend_action": "Reessayer plus tard ou afficher une indisponibilite temporaire.",
    },
    {
        "code": "routing_timeout",
        "http_status": 504,
        "category": "routing",
        "retryable": True,
        "message": "Le moteur OSRM n'a pas repondu assez vite.",
        "frontend_action": "Reessayer avec le meme trajet.",
    },
    {
        "code": "invalid_routing_response",
        "http_status": 502,
        "category": "routing",
        "retryable": True,
        "message": "La reponse du moteur OSRM est invalide.",
        "frontend_action": "Reessayer ou signaler l'incident.",
    },
    {
        "code": "internal_error",
        "http_status": 500,
        "category": "server",
        "retryable": True,
        "message": "Erreur interne DiddiMap.",
        "frontend_action": "Reessayer plus tard et conserver le contexte utilisateur.",
    },
]
